version: "3.7"

services:
  flask:
    container_name: flask
    restart: always
    build: ./flask
    environment:
      - APP_NAME=PythonFlaskNginxUWSGI
    expose:
      - 8080
    volumes:
      - "./flask/app:/ground0/app"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
